spring:
  profiles:
    active: local
  application:
    name: incial- backend


  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ===========================
# JWT Configuration
# ===========================
jwt:
  secret: ${JWT_SECRET}

# ===========================
# Google OAuth Configuration
# ===========================
google:
  client:
    id: ${GOOGLE_CLIENT_ID:}

# ===========================
# Logging
# ===========================
logging:
  level:
    com.incial.crm: DEBUG
    org.springframework.security: DEBUG

# ===========================
# Swagger Configuration
# ===========================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# ===========================
# For Envs
# ===========================

env:
  printer:
    enabled: true
    endpoint-enabled: true