version: "3.8"

services:
  app:
    build: .
    container_name: incial-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${NEON_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${NEON_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${NEON_DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
